# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19uHXuTpqCRWpS_3ZmuDNOOx5x8IQ_85W
"""

from google.colab import files
import pandas as pd

uploaded = files.upload()

df = pd.read_csv('imu_wrist_training_data.csv')
print(df.shape)
print(df.head())

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Binary labels: 0 = no tremor, 1 = tremor
y = (df['updrs_score'] > 0).astype(int)

# The 3 features the model uses
X = df[['log_power_4_6hz', 'rms_magnitude', 'dominant_frequency']].values

# 80/20 split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Normalise
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(f"Train: {X_train.shape}, Test: {X_test.shape}")

import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Dense(8, activation='relu', input_shape=(3,)),
    tf.keras.layers.Dense(4, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=32,
    verbose=1
)

loss, acc = model.evaluate(X_test, y_test)
print(f"\nTest accuracy: {acc*100:.1f}%")

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

with open('tremor_model.tflite', 'wb') as f:
    f.write(tflite_model)

print(f"Model size: {len(tflite_model)} bytes")

hex_bytes = [f'0x{b:02x}' for b in tflite_model]
lines = []
for i in range(0, len(hex_bytes), 12):
    lines.append('  ' + ', '.join(hex_bytes[i:i+12]))

c_code = (
    '// Auto-generated TFLite model\n'
    'const unsigned char model_data[] = {\n'
    + ',\n'.join(lines) + '\n'
    '};\n'
    f'const unsigned int model_data_len = {len(tflite_model)};\n'
)

with open('model_data.h', 'w') as f:
    f.write(c_code)

print("model_data.h created")
print(f"Array size: {len(tflite_model)} bytes")

print("// Paste these into your Arduino sketch:\n")
print(f"const float FEATURE_MEAN[3] = {{{scaler.mean_[0]:.6f}f, {scaler.mean_[1]:.6f}f, {scaler.mean_[2]:.6f}f}};")
print(f"const float FEATURE_STD[3]  = {{{scaler.scale_[0]:.6f}f, {scaler.scale_[1]:.6f}f, {scaler.scale_[2]:.6f}f}};")

files.download('model_data.h')
files.download('tremor_model.tflite')

weights_c = "// Auto-generated model weights - DO NOT EDIT\n\n"

layer_names = ['layer1', 'layer2', 'layer3']

for i, layer in enumerate(model.layers):
    w = layer.get_weights()
    kernel = w[0]
    bias = w[1]

    rows, cols = kernel.shape
    weights_c += f"const float {layer_names[i]}_weights[{rows}][{cols}] = {{\n"
    for row in kernel:
        weights_c += "  {" + ", ".join([f"{v:.6f}f" for v in row]) + "},\n"
    weights_c += "};\n\n"

    weights_c += f"const float {layer_names[i]}_bias[{bias.shape[0]}] = {{"
    weights_c += ", ".join([f"{v:.6f}f" for v in bias])
    weights_c += "};\n\n"

weights_c += f"const float FEATURE_MEAN[3] = {{{scaler.mean_[0]:.6f}f, {scaler.mean_[1]:.6f}f, {scaler.mean_[2]:.6f}f}};\n"
weights_c += f"const float FEATURE_STD[3]  = {{{scaler.scale_[0]:.6f}f, {scaler.scale_[1]:.6f}f, {scaler.scale_[2]:.6f}f}};\n"

with open('model_weights.h', 'w') as f:
    f.write(weights_c)

files.download('model_weights.h')
print("Done - model_weights.h downloaded")